{
  "stored": "$statement.stored",
  "agent": "$statement.actor.mbox",
  "NT": "$statement.actor.name",
  "Monitoring Summary": "$statement.object.definition.extensions.https://qook&46;test&46;salt&46;ch/tm/monitoringSummary",
  "monitoring Type": "$statement.object.definition.extensions.https://qook&46;test&46;salt&46;ch/tm/monitoringType",
  "Transction summary": "$statement.object.definition.extensions.https://qook&46;test&46;salt&46;ch/tm/transactionSummary",
  "timestamp": "$statement.timestamp",
  "version": "$statement.version",
  "coach": "$statement.context.instructor.mbox",
  "_id": 1,
  "id": "$statement.id",
  "monitoring Reason": "$statement.object.definition.extensions.https://qook&46;test&46;salt&46;ch/tm/monitoringReason",
  "result": "$statement.result.score.scaled",
  "verb": "$statement.verb.display.en",
  "transactionType": "$statement.object.id",
  "common_opening_opening": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;opening&46;opening",
  "common_opening_identification": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;opening&46;identification",
  "common_resolution_system": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;resolution&46;system",
  "common_resolution_diagnostic": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;resolution&46;diagnostic",
  "common_resolution_proactivity": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;resolution&46;proactivity",
  "common_resolution_solution": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;resolution&46;solution",
  "common_communication_professionalism": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;communication&46;professionalism",
  "common_communication_softskills": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;communication&46;softskills",
  "common_communication_structure": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;communication&46;structure",
  "common_closing_closing": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;closing&46;closing",
  "case_communication_contact": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;communication&46;contact",
  "case_closing_processingTime": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;closing&46;processingtime",
      "inbound_sales_validation": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;sales&46;validation",
  "inbound_sales_opportunity": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;sales&46;opportunity",
  "inbound_sales_argumentation": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;sales&46;argumentation",
  "inbound_communication_listening": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;communication&46;listening",
  "inbound_communication_blanks": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;communication&46;blanks",
  "inbound_communication_speech": "$statement.result.extensions.https://qook&46;test&46;salt&46;ch/tm/content&46;case&46;communication&46;speech"
}